# default_scenario_name: 'Inspection'
# scenarios_data_folder: '/home/nao/ros_robocup_ws/data/scenarios'
# THIS FOLLOWING PATH SHOULD FIT WITH EVERY WORKSPACE
scenarios_data_folder: '../data'
#default_scenario_name: 'TestHRIScenarioV1'
#default_scenario_name: 'InspectionScenarioV1'
#default_scenario_name: 'ReceptionistScenarioV1'
#default_scenario_name: 'ReceptionistScenarioV0'
# default_scenario_name: 'ReceptionistScenarioV3'
default_scenario_name: 'CarryMyLuggageV0'
#default_scenario_name: 'GPSRScenarioV0'
