GeneralManager:
  #config_folder: '/home/jsaraydaryan/ros_robotcupathome_ws/src/data/general_management'
  config_folder: '/home/astro/catkin_robocup2018/data/general_management'
  #current_scenario: 'COCKTAIL_PARTY'
  #current_scenario: 'TEST_NAVIG'
  #current_scenario: 'DOOR_OPENED_NAVIG'
  #current_scenario: 'TEST_DIALOGUE'
  #current_scenario: 'TEST_COCKTAIL_PARTY_V2'
  #current_scenario: 'TEST_COCKTAIL_PARTY_V3'
  #current_scenario: 'TEST_HOOMANO'
  #current_scenario: 'SPRV1'
  current_scenario: 'SPRV2'
  #current_scenario: 'INSPECTION'
  #current_scenario: 'GPRSV1'
  #current_scenario: 'GPRSV2CPE'
  


  
  
  
  
  

  
  

  